name: Update Ranking

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v3

      - name: Instalar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Atualizar ranking
        run: ruby update_ranking.rb

      - name: Commit e Push
        run: |
          git config --global user.name "RankingBot"
          git config --global user.email "bot@example.com"
          git add .
          git commit -m "Ranking atualizado automaticamente" || echo "Nada para commitar"
          git push https://$GH_TOKEN@github.com/SaiyanWorldRPG/SaiyanWorld-RankingAPI.git HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}