name: Update Ranking

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Garantir que ranking.json existe
        run: |
          if [ ! -f ranking.json ]; then
            echo '{ "players": {} }' > ranking.json
          fi

      - name: Instalar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Atualizar ranking
        run: ruby update_ranking.rb

      - name: Commit e Push
        run: |
          git config --global user.name "RankingBot"
          git config --global user.email "bot@example.com"
          git add ranking.json
          git commit -m "Ranking atualizado automaticamente" || echo "Nada para commitar"
          git push https://$GH_TOKEN@github.com/SaiyanWorldRPG/SaiyanWorld-RankingAPI.git HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
